### PR TITLE
Docs->Architecture->pbmm->architecture.md : adjusted endpoint vpc 2nd AZ subnet name

### PR DESCRIPTION
**Pull request by ipnextgen**
2nd AZ Subnet name was also "a" instead of "b"

### CODE REVIEW

**Comment by rjjaegeraws** [comment]
Thanks for putting an update. It looks like the formatting of the Route table got lost? Could have something to do with the draw.io host name 'drawio.corp.amazon.com'.

**Comment by ipnextgen** [comment]
Hi,

Didn't notice it in the local version. Let me try to fix.

**Comment by ipnextgen** [comment]
@rjjaegeraws  I think it looks good now.

**Review by rjjaegeraws — APPROVED** [review]
Looks good. thanks.

**Pull request merged**
