### PR TITLE
Removed SCP removal from accounts

### PR DESCRIPTION
**Pull request by charliejllewellyn**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rjjaegeraws** [comment]
Hey,

What is the driver for this change?

**Comment by Brian969** [comment]
Hey Ryan - The SEA is currently erroneously removing customer applied 'account' level SCP's on SM execution.  I asked Charlie to take a shot a fixing.

**Review by Brian969 — APPROVED** [review]
LGTM - stops removal of customer account level SCP's on SM execution

**Comment by Brian969** [comment]
- This fix appears to work - preventing customer supplied SCPs from being removed from unmanaged accounts on SM execution
- While the SM removes extra policies from managed ou's and accounts, the "OnPolicyChange" event doesn't...

**Pull request merged**
