### PR TITLE
(config): config and doc update for asymmetric routing with GWLB 

### PR DESCRIPTION
**Pull request by rjjaegeraws**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

This pull request updates the documentation and sample config file to include additional route in the 'onprem' perimeter route tables.

### CODE REVIEW

**Comment by Brian969** [comment]
FYI - you also need to remove the CIDR ranges from the cidr-pools, or they could get double assigned.

**Comment by rjjaegeraws** [comment]
> FYI - you also need to remove the CIDR ranges from the cidr-pools, or they could get double assigned.

done. removed it from the cidr pool.

**Comment by Brian969** [comment]
We still have a problem with 10.7.4.0/22 for which I'm not sure how to easily deal with :-(.  Holding off merging until we have a plan.

**Review by archikierstead — APPROVED** [review]
LGTM

**Comment by archikierstead** [comment]
Thank you for contributing to ASEA. Note that customers should look at using [Landing Zone Accelerator on AWS (LZA)](https://aws.amazon.com/solutions/implementations/landing-zone-accelerator-on-aws/) We're currently only merging security and critical bug fixes. However all ASEA PRs and Issues are noted by the LZA team while developing that solution. Thank you!

**Pull request closed without merging**
