### PR TITLE
CI/CD Performance Enhancement

### PR DESCRIPTION
**Pull request by antoineaws**
- Adds .eslintrc.js to each project
- Speeds up internal ci/cd pipeline by 340% (45m to ~13m)

### CODE REVIEW

**Comment by Brian969** [comment]
@fredbonin - Antoine figured out how to bring down the time it takes eslint in the ci/cd pipeline down to about 6-7min - 20+minutes is insanely frustrating. He ended up adding the .eslintrc to each project, for some reason having only 1 was making the eslint go hunting for references for a long time. Adding them to each project dropped each from 20-30 sec to 5-6 seconds each. Is this a good approach? How do we ensure each project has the same eslint settings? Do we add a script to auto-add and update these as projects are added?

**Comment by antawad** [comment]
This is ready for review. Main modification is parallelizing lint and typecheck.

**Comment by Brian969** [comment]
45 minutes to 13minutes is very impressive!

**Comment by antoineaws** [comment]
Note for future reference, as the solution moves to sdk v3 and starts importing specific sdk libraries for each project, it will improve compilation time for the "Typecheck" step which recursively run `pnpx tsc --noEmit`. The compilation time gets better since tsc will spend less time on i/o,parse,bind and check. 

Comparison below of a random project compile time (note `Total time`).

**SDK Currently in-use v2**
```
Files:                         445
Lines of Library:             8102
Lines of Definitions:       553661
Lines of TypeScript:           259
...
Nodes of Library:            22493
Nodes of Definitions:      1619617
Nodes of TypeScript:           928
...
Identifiers:                601234
Symbols:                    377991
Types:                      131593
Instantiations:              12546
Memory used:               597267K
Assignability cache size:     5199
Identity cache size:             5
Subtype cache size:             13
Strict subtype cache size:       0
I/O Read time:               0.38s
Parse time:                  2.85s
ResolveModule time:          0.36s
ResolveTypeReference time:   0.01s
Program time:                3.68s
Bind time:                   0.98s
Check time:                  2.90s
printTime time:              0.00s
Emit time:                   0.00s
Total time:                  7.56s

real    0m8.077s
user    0m11.336s
sys     0m0.757s
```
**SDK v3**
```
Files:                        426
Lines of Library:            8102
Lines of Definitions:       47212
Lines of TypeScript:          258
...
Nodes of Library:           22493
Nodes of Definitions:      151928
Nodes of TypeScript:          916
...
Identifiers:                59080
Symbols:                    53415
Types:                      17724
Instantiations:             11909
Memory used:               95829K
Assignability cache size:    3391
Identity cache size:            5
Subtype cache size:            13
Strict subtype cache size:      0
I/O Read time:              0.07s
Parse time:                 0.59s
ResolveModule time:         0.37s
ResolveTypeReference time:  0.01s
Program time:               1.09s
Bind time:                  0.27s
Check time:                 1.14s
printTime time:             0.00s
Emit time:                  0.00s
Total time:                 2.50s

real    0m2.895s
user    0m4.756s
sys     0m0.273s
```

**Comment by fredbonin** [comment]
Please don't merge this PR yet, I found an alternative that might reduce the time even more (still need to investigate more though). 

It also does not require new .eslintrc.js for each project.

**Comment by fredbonin** [comment]
Hi,
Here is the PR that reduce the time even further : https://github.com/aws-samples/aws-secure-environment-accelerator/pull/852. I suggest that we close this one and merge the other one instead.

**Comment by antoineaws** [comment]
Closed in favor of #852

**Pull request closed without merging**
