### PR TITLE
fix(core): Ou-Validation Timeout

### PR DESCRIPTION
**Pull request by naveenkoppula**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by archikierstead — COMMENTED** [review]
Why are we bumping prettier to 2.2.0?  That version was released only hours ago.

**Review by archikierstead — APPROVED** [review]
LGTM

**Comment by naveenkoppula** [comment]
> Why are we bumping prettier to 2.2.0? That version was released only hours ago.

Prettier is the issue for timing out Ov-Validation when the config file is large and YAML format. It will be an issue for JSON also but not for >3000 lines. I tested by bumping the prettier version but that is not the fix for this issue (Found nothing related to performance in prettier release notes 2.2.0).  Increasing Lambda Memory is the fix.

I didn't think about issues come with 2.2.0 since it is their public release. But you are true it may not be stable since it is released one day ago. 

Can I change the version to  "2.1.2"?

Reference:

https://www.npmjs.com/package/prettier
https://github.com/prettier/prettier/issues/4776

**Comment by Brian969** [comment]
- Adding a link to some good general dependency update guidance (provided by James): https://softwareengineering.stackexchange.com/questions/340705/when-should-dependencies-be-updated
- The projects primary motivator for upgrading dependencies on an *adhoc* basis is we need a new API/feature/fix.  We also attempt to follow a semi-annual to annual assessment/update to ensure we don't get too far out-of-date and to ensure all libraries remain supported.  We attempted to start with the latest LTS versions (like node.js).
- In this case we updated to the latest release to see if their was an undocumented fix to the performance issue.  While it didn't solve the problem, the work to upgrade and test had been completed.  Rather than rollback, it was included as it dealt with the future tech debt.  Given it was a major version bump and *just* released, it likely would have been better to settle on the prior release (2.1.2), which we will pay better attention to in future.
- Great guideance/advice!

**Pull request merged**
